# Generated by Django 3.1.6 on 2021-10-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stiiizy_verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='serial',
            field=models.CharField(max_length=100),
        ),
    ]
